### ISSUE TITLE
Is this package recommended in order to build a company-wide coding standard

### ISSUE THREAD

**Issue by greg0ire** [ergebnis/php-cs-fixer-config#793]
I was looking for a way to build a custom ruleset for my company, following a discussion about https://cs.symfony.com/doc/rules/function_notation/nullable_type_declaration_for_default_null_value.html : many of us think the default for that rule is wrong, and I thought it would be good to build our own ruleset based on Symfony. After searching the web, I landed here _via_ [this stack overflow question](https://stackoverflow.com/questions/44715387/how-can-i-create-a-custom-rule-set-for-php-cs-fixer).

I've tested this, and it works great, but now I was wondering how to use this: as a dependency? Or is the intended usage for users that want to benefit from the config factory but build there own ruleset to use https://github.com/ergebnis/php-cs-fixer-config-template as a template. It seems inconvenient, because then we don't get updates on the configuration factory.

What would you recommend in this situation? I've noticed tests that seem like they should be reused such as this one: https://github.com/ergebnis/php-cs-fixer-config/blob/main/test/Unit/RuleSet/ExplicitRuleSetTestCase.php

But they are impossible to reuse unless we use templating, right?

In any case, thanks for sharing this package!

**Comment by localheinz** [comment]
@greg0ire 

I use this package as a dependency in all of my PHP packages and applications. 

Letting a PHP package and application depend on a package like `ergebnis/php-cs-fixer-config` allows you to ship both the configuration and - as an indirect dependency - the appropriate version of `friendsofphp/php-cs-fixer`. 

Instead of adding more rule sets here, I recommend creating a new repository based on `ergebnis/php-cs-fixer-config-template` and evolving one or more rule sets as needed by the team (or company) using it. 

When I help clients with their legacy PHP applications, I often introduce `friendsofphp/php-cs-fixer`, too. When they have a team of developers, I create a new repository based on the template. When they do not have any developers, I use this package here. 

The configuration factory does not evolve much. Most of the value of this package is in having a vehicle for sharing configurations via automated dependency updates, and in the tests that allow discovery of new fixers and configuration options when using the explicit rule sets.

I have also published an article [Sharing configurations for PHP-CS-Fixer across projects](https://localheinz.com/articles/2023/03/10/sharing-configurations-for-php-cs-fixer-across-projects/) on my website, perhaps it helps?

Thank you for your feedback!
